version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: jphish
      POSTGRES_USER: sarthak
      POSTGRES_PASSWORD: sarthak123
    volumes:
      - postgres_db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sarthak"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./JPhish
      dockerfile: Dockerfile.jphish
    container_name: Jphish0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jphish
      SPRING_DATASOURCE_USERNAME: sarthak
      SPRING_DATASOURCE_PASSWORD: sarthak123
    ports:
      - "9000:9000"

volumes:
  postgres_db-data:
