services:
  app:
    build: .
    image: springboot-app
    container_name: campaignService
    ports:
        - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/campaign
      SPRING_DATASOURCE_USERNAME: sarthak
      SPRING_DATASOURCE_PASSWORD: sarthak123
    depends_on:
        - postgres

  postgres:
    image: postgres:14
    container_name: campaign
    ports:
        - "5433:5432"
    environment:
      POSTGRES_DB: campaign
      POSTGRES_USER: sarthak
      POSTGRES_PASSWORD: sarthak123

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: